### ISSUE TITLE
[AUDIO ISSUE] Acer Chromebook 11 C733

### ISSUE THREAD

**Issue by phrmendes** [eupnea-linux/audio-scripts#7]
# Info

- Model: [Amazon Link](https://www.amazon.com/Acer-Chromebook-311-C733-C5AS-11-6/dp/B08766YRQP)
- CPU:  Celeron N4020
-  Code Name: Gemini Lake Refresh

# Problem

After using the `depthboot` script with Ubuntu and Arch with Xfce as desktop environment, audio is not recognized. The `setup-audio` script returns this error for all systems:

```
Traceback (most recent call last):
  File "/usr/local/bin/setup-audio", line 122, in <module>
    sof_audio("glk", user_id)
NameError: name 'user_id' is not defined
```

The `postinstall.service ` isn't fopund and bluetooth isn't working either. 

```
Traceback (most recent call last):
  File "/usr/local/bin/install-to-internal", line 193, in <module>
    post_copy()
  File "/usr/local/bin/install-to-internal", line 117, in post_copy
    cpfile("/etc/postinstall.service", "/mnt/depthboot-internal/etc/systemd/system/postinstall.service")
  File "/usr/local/bin/functions.py", line 110, in cpfile
    raise FileNotFoundError(f"No such file: {src_as_path.absolute().as_posix()}")
FileNotFoundError: No such file: /etc/postinstall.service
```

**Comment by Apacelus** [comment]
* Username issue fixed in https://github.com/eupnea-linux/audio-scripts/commit/18ff508b3ddca8445ec2b963c5eeafa4b1eeff49
* Postinstall service should be fixed in https://github.com/eupnea-linux/postinstall-scripts/commit/8b86b1dc51560fa11c75c60b59354567ee4aeb0d

Run ``update-scripts`` to update and try again.

* Please open a new issue for bluetooth at https://github.com/eupnea-linux/depthboot-builder and upload the output of ``sudo dmesg``
